version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
      - meilisearch
    env_file:
      - backend.env
    ports:
      - "9000:9000"
    volumes:
      - .:/app/medusa
      - node_modules:/app/medusa/node_modules

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    expose:
      - 5432

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  meilisearch:
    image: getmeili/meilisearch:v0.27.1
    restart: unless-stopped
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=fishingtime
    volumes:
      - meilisearch-data:/meili_data
    command:
      - /bin/meilisearch

  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  node_modules:
  minio_storage:
  meilisearch-data:
