version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      JWT_SECRET: fishU78time
      COOKIE_SECRET: fishU78time
      ADMIN_CORS: https://fishingtime-admin.netlify.app`
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app/medusa
      - node_modules:/app/medusa/node_modules

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    expose:
      - 5432

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  minio:
    image: minio/minio:edge
    environment:
      MINIO_ACCESS_KEY: fishU78time
      MINIO_SECRET_KEY: fishU78time
    volumes:
      - datastore:/data
    ports:
      - 8000:8000
    command: server /data

  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  node_modules:
  datastore:
